module.exports = {
  extends: ["@commitlint/config-conventional", "cz"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "init" /* 项目初始化 */,
        "release" /* 发布 */,
        "del" /* 删除代码/文件 */,
        "add" /* 新增依赖 */,
        "ui" /* 更新UI */,
        "feat" /* 新增功能 */,
        "fix" /* 修复bug */,
        "docs" /* 修改文档 */,
        "style" /* 代码样式修改不影响逻辑 */,
        "refactor" /* 代码重构 */,
        "test" /* 增删测试 */,
        "chore" /* 更改配置文件 */,
        "revert" /* 回滚代码 */,
        "breaking change" /* 重大改变 */,
        "types" /* 修改定义文件 */,
        "perf" /* 性能优化 */,
        "build" /* 修改项目构建工具 */,
      ],
    ],
    "type-empty": [2, "never"],
    "type-case": [0],
    "scope-empty": [0],
    "subject-full-stop": [0, "never"],
    "subject-empty": [
      2,
      "never",
    ] /* 提交不符合规范时,也可以提交,但是会有警告 */,
    "subject-case": [0, "never"],
    "scope-case": [2, "always", "lower-case"],
    "header-max-length": [2, "always", 72],
  },
};
