import '../../theme/var.dart';

const cell_font_size = font_size_md;
const double cell_height = 20;
const double cell_vertical_padding = 10;
const cell_horizontal_padding = padding_md;
const cell_text_color = text_color;
const cell_background_color = white;
const cell_border_color = border_color;
const cell_active_color = active_color;
const cell_required_color = danger_color;
const cell_label_color = gray_6;
const cell_label_font_size = font_size_sm;
const cell_label_margin_top = padding_base;
const cell_value_color = gray_6;
const double cell_icon_size = 16;
const cell_right_icon_color = gray_6;
const cell_large_vertical_padding = padding_sm;
const cell_large_title_font_size = font_size_lg;
const cell_large_label_font_size = font_size_md;
